services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # internal network
      - "29092:29092" # host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Bind both listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      # Advertise internal (for Docker) and external (for host) addresses
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  flink-jobmanager:
    image: my-flink-py:1.19.0
    command: jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./flink-job:/opt/pyflink/jobs
      - ./jars:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    depends_on:
      - kafka

  flink-taskmanager:
    image: my-flink-py:1.19.0
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./flink-job:/opt/pyflink/jobs
      - ./jars:/opt/flink/usrlib
    depends_on:
      - flink-jobmanager

  submit-job:
    image: my-flink-py:1.19.0
    depends_on:
      - flink-jobmanager
    volumes:
      - ./flink-job:/opt/pyflink/jobs
      - ./jars:/opt/flink/usrlib
    entrypoint: [ "/bin/bash", "-c", "/opt/flink/bin/flink run -m http://flink-jobmanager:8081 -py /opt/pyflink/jobs/missing_event_job.py --jarfile /opt/flink/usrlib/flink-sql-connector-kafka-3.2.0-1.19.jar" ]

  go-alert-service:
    build: ./go-alert-service
    depends_on:
      - kafka
    environment:
      PAGERDUTY_ROUTING_KEY: ${PAGERDUTY_ROUTING_KEY}
    restart: on-failure

  pinot-controller:
    image: apachepinot/pinot:latest
    container_name: pinot-controller
    command: "StartController -zkAddress zookeeper:2181"
    ports:
      - "9000:9000" # Pinot Controller UI
    environment:
      JAVA_OPTS: "-Xms512M -Xmx512M"
    depends_on:
      - zookeeper

  pinot-broker:
    image: apachepinot/pinot:latest
    container_name: pinot-broker
    command: "StartBroker -zkAddress zookeeper:2181"
    ports:
      - "8099:8099" # Broker query port
    environment:
      JAVA_OPTS: "-Xms512M -Xmx512M"
    depends_on:
      - pinot-controller

  pinot-server:
    image: apachepinot/pinot:latest
    container_name: pinot-server
    command: "StartServer -zkAddress zookeeper:2181"
    ports:
      - "8098:8098" # Server admin port
    environment:
      JAVA_OPTS: "-Xms1G -Xmx1G"
    depends_on:
      - pinot-broker

  pinot-minion:
    image: apachepinot/pinot:latest
    container_name: pinot-minion
    command: "StartMinion -zkAddress zookeeper:2181"
    environment:
      JAVA_OPTS: "-Xms512M -Xmx512M"
    depends_on:
      - pinot-controller
